travis:
  secure:
    BINSTAR_TOKEN: CD9EAAp3Fm4H93usIXuzddd4VSjBQ4fUyduux28mIdY8PJiO1oj+ag7aWdOJtDq5wsfEhYo2yaoVnUoBbosa5vZgM4cyhJuplIrUsRXWezZrYkb9s0ez/kHxaul5lZSuttcJL8oC70+MrgcfR8ZjGe/QFOtkA5tZpscE8nLvqvTzCzkU+2yBUDOUdKB/gjec0YwHPSqL3lsZ31GgXqnkUN1Fn30V6iltOYhQthKmT9x7oxn9+CdxKIfG3Dmq/K1VZyJbICiC5pXLom9pq3DULHQed6x+ZtKWgy6rQ9NH56ZF9lkTz+YHk4vIkFQh+mlZKFrvOlfGWeWXFTu8z9KNPLxr9TJErFY62ypqOJX42lmbZxIYSmzK/+hB5Y0YVar/416t5onpW75BodjnZ79QpeD8znlvFnX8i/QoOme+VVAeZirScovehkgmcTtbz5Nv+BDUoqudD4YMEjb+m8iFeC4gpHHto98j12CTmi5YOK25IY7U+a8eow0WdN0bcr8vlgbibgct98I29v0IwkGMNJ8/zTBrmUElSxUPDWLhP53etnIkj7JaY0KCS5NOeVEMM4aVffc6qV0vvj6KvXcJyFigD4cFiCPdia2gzPiC9y10PQ/+p3yMwGxz/1JpCmWQhatyYQtQiSeCpvLdZ/cNT50d/VZB/jywi05oc3lyXak=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
