travis:
  secure:
    BINSTAR_TOKEN: CaVgXsM+pRPdmImCsQJygf7+mHenfNsJb90lCkqGjxeamRkB875BM9m/M4we6xNllOtaS74gWfS7Di+tXDy60heBj2bHaNgYgh7xuXKFfEnOL3PwF0SDBF301RuVFVDOroYyBd7R9vqVHaaR+ha20laI7GCHd+RR9Aj5VyTmlYYjQJUiFFLfnaUJUkTjvevogEpdDgEK7cYAoGO9qF6QDz+brGHUq0jU4aIWdfYgynoMhC7ThgjUlX4ge0ZZXfuhfvK+vsCcJg57MilCIbArwxIf4UhUlwHGp6YJOXmORJ0OzMC/SXku9oJRcUgpd9BkPhZoLAsmCwBJNRaY7II8MA2xVwCNOpj1FqrfG+lMYUAH1qQ8Vr43ktoi5CBsmm+1c3UMdAYzeu4hYSyuigD7u62GQco84AfaBrH6tvAZYR52A0/G98oKIsgHYGLaSIlAYe8VX6Dvv/RMf5MspE7whMrHNXtKkpIb2ifwT9iOKJ0OXueWliy39SInk4zrpo4ytYu6ziUm/0zj6BJXdSQfRaFCvacwgJBa1A5aly42c6dsm0/iZLSyiutz8hjoBapnO5WsweyEZHF3Oy1Etgi9caVJujae2dshep4uFKNqc3ON7ZXcTeN1J0o3F3/Y7OGNcy2c+VyHjKJN6XeopKHcw0ltRRctZl1cZJCCr9juv5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
